import Navbar from "@/features/navbar";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { type ReactNode, StrictMode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// !Google Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
});

// !Props
interface Props {
  children: ReactNode;
}

// !Root layout
export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <StrictMode>
          <Navbar />
          {children}
        </StrictMode>
      </body>
    </html>
  );
}
