name: Lint the codebase

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    strategy:
      matrix:
        pnpm-version: [10]
        node-version: [21, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]

      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm version ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: "${{matrix.pnpm-version}}"

      - name: Use node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate prisma client
        run: pnpm prisma generate

      - name: Lint the code using biome
        run: pnpm lint

  typecheck:
    strategy:
      matrix:
        pnpm-version: [10]
        node-version: [21, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]

      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm version ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: ${{matrix.pnpm-version}}

      - name: Use node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate prisma client
        run: pnpm prisma generate

      - name: Typecheck the code using typescript
        run: pnpm typecheck
