name: Test the codebase

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-unit-and-integration:
    name: Test Unit and Integration
    strategy:
      matrix:
        pnpm-version: [9]
        node-version: [21, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm version ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: ${{matrix.pnpm-version}}
      - name: Use node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint the code using biome
        run: pnpm test
  test-e2e:
    name: Test E2E
    strategy:
      matrix:
        pnpm-version: [9]
        node-version: [21, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm version ${{matrix.pnpm-version}}
        uses: pnpm/action-setup@v4
        with:
          version: ${{matrix.pnpm-version}}
      - name: Use node ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm start
